### ISSUE TITLE
possible to use with public bridged network?

### ISSUE THREAD

**Issue by ijstokes** [BerlinVagrant/vagrant-dns#25]
I have my vagrant-configured VMs using "public" networking through a network bridge, so they are in the same 192.168.1.0 network.  I would love to be able to access these VMs by name from the host system (my laptop) using vagrant-dns:

``` bash
scp foo.dat vm1.dev:.
ssh vm2.dev
```

My `Vagrantfile` look like this:

``` ruby
  config.dns.tld = "dev"
  config.vm.hostname = "cathy"
  config.vm.network :public_network, :bridge => 'en1: USB Ethernet', :mac => "00000C00000C", :ip => "192.168.1.32"
  config.vm.box = "precise64"
```

TIA for any suggestions how to cope with this!

**Comment by fnordfish** [comment]
That's an old one, I''m sorry if that's spamming you. 

Support for `public_network` was added in v1.1.0, since v2.1.0 this is actually part of our test suite:

```ruby
config.vm.network :public_network, ip: '10.10.10.102', bridge: "en0: Wi-Fi (AirPort)"
```
