### ISSUE TITLE
multi-machine support

### ISSUE THREAD

**Issue by mbizkit76** [BerlinVagrant/vagrant-dns#30]
It would be very useful if this plugin could support multi machines enviroments
At the time it seems not possible

**Comment by jonashackt** [comment]
For me, a Vagrant multi-machine setup is also fully working. You can check the Vagrantfile here https://github.com/jonashackt/ansible-windows-docker-springboot/blob/master/step4-windows-linux-multimachine-vagrant-docker-swarm-setup/Vagrantfile. It comprises of 2 Ubuntu and 2 Windows Server 1709 boxes, which use this Plugin for later DNS resolution with Traefik proxy. See the full example here: https://github.com/jonashackt/ansible-windows-docker-springboot
