### ISSUE TITLE
Tag as v1.0.0 and beyond

### ISSUE THREAD

**Issue by pda** [BerlinVagrant/vagrant-dns#34]
As people are using this out in the wild, it'd be great to tag a v1.0.0 release, and follow [semver](http://semver.org/) from there.

See also: https://github.com/ioquatix/rubydns/issues/28

**Comment by fnordfish** [comment]
Missed the rubydns 1.0 release. vagrant-dns 1.0.0 has been released with rubydns 1.0.2
Thanks for your patience.
