### ISSUE TITLE
Broken on Vagrant 1.7.4?

### ISSUE THREAD

**Issue by justicel** [BerlinVagrant/vagrant-dns#38]
Hello, have you tested this with vagrant 1.7.4? It appears to be broken and consistently attempts to start dns on port 53, regardless of the configuration:

5030 I, [2015-08-12T12:57:05.656941 #39031]  INFO -- : Starting RubyDNS server (v0.9.4)...
5031 I, [2015-08-12T12:57:05.657133 #39031]  INFO -- : <> Listening on udp:0.0.0.0:53
5032 E, [2015-08-12T12:57:05.658072 #39031] ERROR -- : Actor crashed!
5033 Errno::EACCES: Permission denied - bind(2)
5034   /Users/jlondon/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/handler.rb:130:in `initialize'
5035   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `public_send'
5036   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `dispatch'
5037   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:79:in `dispatch'
5038   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:60:in `block in invoke'
5039   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:71:in `block in task'
5040   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/actor.rb:357:in `block in task'
5041   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks.rb:57:in `block in initialize'
5042   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks/task_fiber.rb:14:in `block in create'
5043 E, [2015-08-12T12:57:05.658471 #39031] ERROR -- : Actor crashed!
5044 Errno::EACCES: Permission denied - bind(2)
5045   /Users/jlondon/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/handler.rb:130:in `initialize'
5046   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `public_send'
5047   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `dispatch'
5048   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:79:in `dispatch'
5049   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:60:in `block in invoke'
5050   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:71:in `block in task'
5051   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/actor.rb:357:in `block in task'
5052   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks.rb:57:in `block in initialize'
5053   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks/task_fiber.rb:14:in `block in create'
5054   (celluloid):0:in `remote procedure call'
5055   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:108:in `value'
5056   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
5057   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
5058   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid.rb:173:in `new'
5059   /Users/jlondon/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:166:in `block in run'
5060   /Users/jlondon/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:147:in `each'
5061   /Users/jlondon/.vagrant.d/gems/gems/rubydns-0.9.4/lib/rubydns/server.rb:147:in `run'
5062   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `public_send'
5063   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:26:in `dispatch'
5064   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/calls.rb:79:in `dispatch'
5065   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:60:in `block in invoke'
5066   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/cell.rb:71:in `block in task'
5067   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/actor.rb:357:in `block in task'
5068   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks.rb:57:in `block in initialize'
5069   /Users/jlondon/.vagrant.d/gems/gems/celluloid-0.16.1/lib/celluloid/tasks/task_fiber.rb:14:in `block in create'

**Comment by justicel** [comment]
Figured out what it is. It's not specifically your issue, but rubydns appears to be broken with celluloid 0.16.1 which was released a few days ago. Can you lock your dependency to celluloid 0.16.0 which fixes this? It should work with the fuzzy match in rubydns and that way we/you won't have to wait for this to be resolved by two separate gems :)

**Comment by ioquatix** [comment]
It's not that RubyDNS is broken with Celluloid, it's that Celluloid 0.16.1 completely changes the supervision API :)

For more details see https://github.com/ioquatix/rubydns/issues/55#issuecomment-132612867

**Comment by fnordfish** [comment]
Hello all,

Thanks a lot for reporting and debugging this issue. I've just released an update.
