### ISSUE TITLE
https is not working

### ISSUE THREAD

**Issue by itsazzad** [BerlinVagrant/vagrant-dns#40]
How to make it work with https/ssl?

**Comment by fnordfish** [comment]
vagrant-dns does really only provide a DNS lookup. Any http/https comes way behind the name lookup part. My guess is, that you are using some program which does it's own kind of dns lookup and does not use the system provided by MacOS.
Also, in some cases it's just a caching issue. Try to reset OS X DNS cache: https://support.apple.com/en-us/HT202516
