### ISSUE TITLE
fork() function is unimplemented on this machine (NotImplementedError)

### ISSUE THREAD

**Issue by raupie** [BerlinVagrant/vagrant-dns#41]
I tried this plugin on my windows machine and it crashed due to the error: Error occurred: fork() function is unimplemented on this machine. 

I uninstalled the plugin and my vagrant machine works fine again.

**Comment by fnordfish** [comment]
Sorry, but as stated at the very end of the readme, vagrant-dns runs on MacOS X hosts only. If you'd like to know more about this, please read this document: https://github.com/BerlinVagrant/vagrant-dns/blob/master/PLATFORM_SUPPORT.md

**Comment by fnordfish** [comment]
One more thing. Maybe I've got you wrong and you had vagrant-dns working before? If so, very cool! There might be a lot of potential points where this could go wrong. It would be great if you could give a stacktrace of `vagrant dns --start --debug`

**Comment by raupie** [comment]
It wasn't working. i found another vagrant plugin that accomplished the dhcp host update. Thanks!
