### ISSUE TITLE
Faild to load the "vagrant-dns"

### ISSUE THREAD

**Issue by loncar** [BerlinVagrant/vagrant-dns#42]
Hi,
I have the following log error on every vagrant command :

 INFO environment: Loading plugin from JSON: vagrant-dns
ERROR root: Failed to load plugin: vagrant-dns
ERROR root:  -- Error: #<SyntaxError: /home/<user>/.vagrant.d/gems/gems/vagrant-dns-1.0.0/lib/vagrant-dns/installers/mac.rb:4: unknown type of %string
      EXEC_STYLES = %i{osa sudo}
                       ^
/home/<user>/.vagrant.d/gems/gems/vagrant-dns-1.0.0/lib/vagrant-dns/installers/mac.rb:4: syntax error, unexpected $end
      EXEC_STYLES = %i{osa sudo}
                       ^>
ERROR root:  -- Backtrace:
ERROR root: /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
/home/<user>/.vagrant.d/gems/gems/vagrant-dns-1.0.0/lib/vagrant-dns.rb:5:in `<top (required)>'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
/usr/lib/ruby/vendor_ruby/vagrant.rb:204:in `require_plugin'
/usr/lib/ruby/vendor_ruby/vagrant/environment.rb:760:in `block in load_plugins'
/usr/lib/ruby/vendor_ruby/vagrant/environment.rb:751:in `each'
/usr/lib/ruby/vendor_ruby/vagrant/environment.rb:751:in `load_plugins'
/usr/lib/ruby/vendor_ruby/vagrant/environment.rb:132:in `initialize'
/usr/bin/vagrant:105:in `new'
/usr/bin/vagrant:105:in `<main>'
 INFO interface: error: Failed to load the "vagrant-dns" plugin. View logs for more details.

Version of Vagrant 1.4.3
OS : Linux karnel : 3.16.0-59-generic - Elementary OS 0.3.2 Freya (64-bit)
VBox : 4.3

Thanks

**Comment by fnordfish** [comment]
Hi,

Is it possible for you to upgrade vagrant?
1.4 is kind of old and ships with an old ruby possibly causing this error. 
Afaik, there is no good way of requiring a vagrant version from a plugin :(

If upgrading vagrant is not an option, You'd need to install an older version of vagrant-dns. (Will update this thread with more details after figuring out what version that is)

Robert

**Comment by loncar** [comment]
@fnordfish thanks for quick reply. Version was problem, so I have removed that one and install latest Vagrant version 1.8.1, now everything works fine. Thanks again :)

Best regards,
Nikola
