### ISSUE TITLE
Wildcard subdomain with vagrant  Version 5.0.16 r105871 not seems to be working

### ISSUE THREAD

**Issue by itsazzad** [BerlinVagrant/vagrant-dns#43]
I am in need to support wildcard subdomains. Suppose `example.dev` is my domain name. And I wanna `any.example.dev` should also be working. I tried below. Some months ago it worked may be. But now its not working may be because of the latest vagrant?

```
  config.dns.tld = "dev"
  config.vm.hostname = "example"
  config.dns.patterns = [/^.*example.dev$/]
```

**Comment by fnordfish** [comment]
Hi. No vagrant has pretty much nothing to say in that regard. Your config should work for your case. A known issue is, that when you have (or had) multiple boxes configured with alike dns patterns, vagrant-dns might pick an old IP.  

You can try cleaning up those config files: `~/.vagrant.d/tmp/dns/resolver/*` by manually deleting conflicting lines (or deleting all the lines)  
Don't forget to restart vagrant-dns.  

--  
Robert Schulze
