### ISSUE TITLE
RubyDNS 2.0.0-rc1

### ISSUE THREAD

**Issue by ioquatix** [BerlinVagrant/vagrant-dns#48]
This update is a big improvement to stability, if you have time to try it out and report any issues that would be great.

It removes `celluloid`/`celluloid-dns` as a dependency, and adds `async`/`async-dns` instead. I wrote these because I was disappointed with the direction of celluloid, the many bugs, and design problems it has, which have not been fixed in over 2 years.

**Comment by fnordfish** [comment]
I've just released 2.0.0.rc1 (which requires vagrant 1.9.6)

**Comment by ioquatix** [comment]
RubyDNS 2.0.0 has been released. The only user visible change was that the option `listen:` is now the first argument.

**Comment by ioquatix** [comment]
Just FYI, the use of `listen:` is supported, but deprecated.

**Comment by fnordfish** [comment]
Finally managed to get this wrapped up.

```
vagrant plugin update vagrant-dns
Updating plugins: vagrant-dns. This may take a few minutes...
Fetching: timers-4.1.2.gem (100%)
Fetching: async-1.2.0.gem (100%)
Fetching: async-io-1.0.0.gem (100%)
Fetching: async-dns-1.0.0.gem (100%)
Fetching: rubydns-2.0.1.gem (100%)
Fetching: vagrant-dns-2.0.0.gem (100%)
Successfully uninstalled celluloid-0.16.0
Successfully uninstalled celluloid-io-0.16.2
Removing rubydns-check
Successfully uninstalled rubydns-1.0.3
Successfully uninstalled timers-4.0.4
Successfully uninstalled vagrant-dns-1.1.0
Updated 'vagrant-dns' to version '2.0.0'!
```
🎉

**Comment by ioquatix** [comment]
Awesome!!
