### ISSUE TITLE
DNS names not visible inside box

### ISSUE THREAD

**Issue by bertramn** [BerlinVagrant/vagrant-dns#57]
In your README file you state _"Not visible inside the box"_, which at least for Virtualbox you can easily fix by adding the provisioning flag `--natdnshostresolver1=on`. So below virtualbox provisioner configuration would switch this on for you and then you can DNS resolve against RubyDNS from within this and any other box you may start with this configuration switch.

```rb
config.vm.provider "virtualbox" do |vb|
  vb.gui = false
  vb.name = "mybox"
  vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on", "--vrde", "off", "--vram", 10]
end
```

Checking

```sh
[vagrant@mybox ~]$ ping -c 1 mybox.vagrant.dev
PING mybox.vagrant.dev (192.168.34.188) 56(84) bytes of data.
64 bytes from 192.168.34.188: icmp_seq=1 ttl=64 time=0.015 ms

--- mybox.vagrant.dev ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.015/0.015/0.015/0.000 ms
```

**Comment by fnordfish** [comment]
Thanks, just merged an old PR putting this into the Readme.
