### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by rgarrigue** [BerlinVagrant/vagrant-dns#61]
Hi

I know it's quite unlikely you'ld do it, but please add Windows support

Best regards,

**Comment by fnordfish** [comment]
Hi @rgarrigue 

we'd be happy to provide windows support, but as described in our [PLATFORM_SUPPORT ducument](https://github.com/BerlinVagrant/vagrant-dns/blob/master/PLATFORM_SUPPORT.md) we are personally not very invested in the windows platform and thus have no good idea on how to get windows to play along.
If you are able to give insights of Windows' DNS setup/configuration capabilities and how to automate those, we can give it a try.

**Comment by rgarrigue** [comment]
Thanks @fnordfish for the answer. Sorry I'm not much of a Windows guy myself, can't help there. I guess I'll give a shot at alternative plugin, like vagrant-hostmanager that could do the trick for me. 

Thanks anyway,
