### ISSUE TITLE
Maybe coredns can be DNS server, which have cross-platform support?

### ISSUE THREAD

**Issue by Slach** [BerlinVagrant/vagrant-dns#64]
i known about current limitations but maybe we can view to coredns for support cross-platform features?

**Comment by fnordfish** [comment]
The DNS server part is not the issue for cross-platform support. We use `rubydns` as a server, which is written in ruby (just like vagrant itself).
`vagrant-dns` should just work (as in starting a DNS server on the host) on other platforms, we just don't have a nice way of hooking into the hosts DNS setup. Please see https://github.com/BerlinVagrant/vagrant-dns/blob/master/PLATFORM_SUPPORT.md
