### ISSUE TITLE
Is this project still kicking? :)

### ISSUE THREAD

**Issue by boldandbusted** [BerlinVagrant/vagrant-dns#65]
Howdy. I have been using this plugin for some months, with good success. 🥇  I have some minor bugs to file, but it looks like there's been no movement here since 2018. Is this project still maintained, or was it forked, or it's functions been subsumed by another plugin? Cheers, and thanks for this useful Vagrant plugin.

**Comment by fnordfish** [comment]
Hi. File away :)
This project was low maintenance for some time, but it seems we need to catch up with some changes in vagrant.

Full disclosure: I'm not using vagrant as my daily dev driver any more, making it hard for me to keep up

**Comment by boldandbusted** [comment]
I filed some bugs, and they got fixed! :D Thank you for this project - this has made Vagrant much more viable for more use-cases. 🥳  🎉  🥳  (Yes, I'd like it to work beyond OS X, but I totally understand the reasons for this as stated.) Cheers! (You can close this issue, if you like! 😃  )

**Comment by boldandbusted** [comment]
Hey, thanks for the feedback in March. Things are still working well for me and my use-cases. Cheers!
