### ISSUE TITLE
Getting dynamic IP fails when starting multiple hosts

### ISSUE THREAD

**Issue by mattiasb** [BerlinVagrant/vagrant-dns#78]
Hey!

With the latest 2.4.0 release vagrant-dns works *really* great compared to Landrush on Fedora and Ubuntu. Thanks for that!

One issue a colleague saw today was that given three VMs (kub01.test – kub03.test) the following:
```console
$ vagrant up /kub/ # Or: vagrant up kub0{1..3}.test
```
... gets the correct IP for only *one* of the machines. Which one that is, seems to be a race condition.

For now we just do either:
```console
$ for i in 1 2 3; do vagrant up kub0${i}.test; done
```
... or ...
```console
$ vagrant up /kub/ && vagrant dns -r
```

I tried to understand where the issue comes from but failed unfortunately.

**Comment by fnordfish** [comment]
Do you see any logs? They should be VM specific and look like that:

"[vagrant-dns] Identified DHCP IP as '#{ip}'." or "[vagrant-dns] Could not identify DHCP IP."

**Comment by mattiasb** [comment]
I was a bit stressed when I was looking at the code earlier so it didn't click why I didn't see the messages you mention. Because I saw the debug calls in the code. 

I'll re-run with `VAGRANT_LOG=info` set tomorrow! ☺️

**Comment by mattiasb** [comment]
I searched the logs and it only found an IP address for kub02.test (even though kub01.test and kub03.test was started at the same time):
```console
$ grep "Identified DHCP IP" ./kubes.vagrant.log 
==> kub02.test: [vagrant-dns] Identified DHCP IP as '192.168.121.183'.
 INFO interface: info: [vagrant-dns] Identified DHCP IP as '192.168.121.183'.
 INFO interface: info: ==> kub02.test: [vagrant-dns] Identified DHCP IP as '192.168.121.183'.
 mattiasb  (e) AnsiblePlaybooks-SMAs_4Xa  ~  Documents  
```

We generated the logs like this:
```console
$ export VAGRANT_LOG=info
$ vagrant up /kub/ |& tee kubes.vagrant.log
```

[kubes.vagrant.log](https://github.com/BerlinVagrant/vagrant-dns/files/11230830/kubes.vagrant.log)
